apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: challenge-10
  namespace: szhyhota-locquin
spec:
  rules:
  - host: webnodb.szhyhota-locquin.net4255.luxbulb.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-nodb-service
            port:
              number: 80
  - host: webdb.szhyhota-locquin.net4255.luxbulb.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-service
            port:
              number: 80