namespace: szhyhota-locquin

image:
  repository: slavikz/challenge_4

  tag: v2

mongodb:
  image: mongo:latest
  rootUsername: admin
  rootPassword: pass
  service:
    name: mongodb-service
    port: 27017
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 350Mi
  persistence:
    enabled: true
    storageClass: "longhorn"
    size: 800Mi

app:
  replicas: 3
  service:
    name: app-service
    port: 80
    targetPort: 5000
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 200Mi

appNodb:
  replicas: 1
  service:
    name: app-nodb-service
    port: 80
    targetPort: 5000
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 200Mi

ingress:
  hostWebNodb: webnodb.szhyhota-locquin.net4255.luxbulb.org
  hostWebDb: webdb.szhyhota-locquin.net4255.luxbulb.org
